import * as vscode from 'vscode';
import { assetsConfig } from "./assets_config";
import { assetsFileWriter } from './assets_file_writer';
import { AssetsNode } from './assets_node';

class AssetsGenerator {
    async generate(): Promise<boolean> {
        try {
            const workspaceFolders = vscode.workspace.workspaceFolders;
            if (!workspaceFolders) { return false; }
            const workspaceFolder = workspaceFolders[0];

            const projectUri = workspaceFolder.uri;
            const assetsUri = vscode.Uri.joinPath(workspaceFolder.uri, assetsConfig.assetsPath);
            const outputDirUri = vscode.Uri.joinPath(projectUri, assetsConfig.outputPath);
            const outputFileUri = vscode.Uri.joinPath(outputDirUri, `${assetsConfig.outputName}.dart`);

            let fileContent = '// Generated by Flutter Assets\n\n';

            const stat = await vscode.workspace.fs.stat(assetsUri);
            if (stat.type !== vscode.FileType.Directory) {
                fileContent += "// 'assets-path' should be a dir!";
            } else {
                const assetsNode = await AssetsNode.parseAssets(assetsUri);
                fileContent += assetsNode.toDartFileString(assetsConfig.className, assetsConfig.ignoreExt);
            }

            await assetsFileWriter.write(outputFileUri, fileContent);
            return true;
        } catch (e) {
            console.error(e);
            return false;
        }
    }
}

export var assetsGenerator = new AssetsGenerator();